// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: chat-participant-delete.service.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatParticipantDeleteServiceClient is the client API for ChatParticipantDeleteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatParticipantDeleteServiceClient interface {
	DeleteChatParticipant(ctx context.Context, in *DeleteChatParticipantRequest, opts ...grpc.CallOption) (*DeleteChatParticipantResponse, error)
}

type chatParticipantDeleteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatParticipantDeleteServiceClient(cc grpc.ClientConnInterface) ChatParticipantDeleteServiceClient {
	return &chatParticipantDeleteServiceClient{cc}
}

func (c *chatParticipantDeleteServiceClient) DeleteChatParticipant(ctx context.Context, in *DeleteChatParticipantRequest, opts ...grpc.CallOption) (*DeleteChatParticipantResponse, error) {
	out := new(DeleteChatParticipantResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatParticipantDeleteService/DeleteChatParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatParticipantDeleteServiceServer is the server API for ChatParticipantDeleteService service.
// All implementations must embed UnimplementedChatParticipantDeleteServiceServer
// for forward compatibility
type ChatParticipantDeleteServiceServer interface {
	DeleteChatParticipant(context.Context, *DeleteChatParticipantRequest) (*DeleteChatParticipantResponse, error)
	mustEmbedUnimplementedChatParticipantDeleteServiceServer()
}

// UnimplementedChatParticipantDeleteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatParticipantDeleteServiceServer struct {
}

func (UnimplementedChatParticipantDeleteServiceServer) DeleteChatParticipant(context.Context, *DeleteChatParticipantRequest) (*DeleteChatParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChatParticipant not implemented")
}
func (UnimplementedChatParticipantDeleteServiceServer) mustEmbedUnimplementedChatParticipantDeleteServiceServer() {
}

// UnsafeChatParticipantDeleteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatParticipantDeleteServiceServer will
// result in compilation errors.
type UnsafeChatParticipantDeleteServiceServer interface {
	mustEmbedUnimplementedChatParticipantDeleteServiceServer()
}

func RegisterChatParticipantDeleteServiceServer(s grpc.ServiceRegistrar, srv ChatParticipantDeleteServiceServer) {
	s.RegisterService(&ChatParticipantDeleteService_ServiceDesc, srv)
}

func _ChatParticipantDeleteService_DeleteChatParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatParticipantDeleteServiceServer).DeleteChatParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatParticipantDeleteService/DeleteChatParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatParticipantDeleteServiceServer).DeleteChatParticipant(ctx, req.(*DeleteChatParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatParticipantDeleteService_ServiceDesc is the grpc.ServiceDesc for ChatParticipantDeleteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatParticipantDeleteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatParticipantDeleteService",
	HandlerType: (*ChatParticipantDeleteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteChatParticipant",
			Handler:    _ChatParticipantDeleteService_DeleteChatParticipant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-participant-delete.service.proto",
}
