// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: chat-room-delete.service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRoomDeleteEventType int32

const (
	ChatRoomDeleteEventType_DELETE_CHAT_ROOM  ChatRoomDeleteEventType = 0
	ChatRoomDeleteEventType_CHAT_ROOM_DELETED ChatRoomDeleteEventType = 1
)

// Enum value maps for ChatRoomDeleteEventType.
var (
	ChatRoomDeleteEventType_name = map[int32]string{
		0: "DELETE_CHAT_ROOM",
		1: "CHAT_ROOM_DELETED",
	}
	ChatRoomDeleteEventType_value = map[string]int32{
		"DELETE_CHAT_ROOM":  0,
		"CHAT_ROOM_DELETED": 1,
	}
)

func (x ChatRoomDeleteEventType) Enum() *ChatRoomDeleteEventType {
	p := new(ChatRoomDeleteEventType)
	*p = x
	return p
}

func (x ChatRoomDeleteEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRoomDeleteEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_room_delete_service_proto_enumTypes[0].Descriptor()
}

func (ChatRoomDeleteEventType) Type() protoreflect.EnumType {
	return &file_chat_room_delete_service_proto_enumTypes[0]
}

func (x ChatRoomDeleteEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRoomDeleteEventType.Descriptor instead.
func (ChatRoomDeleteEventType) EnumDescriptor() ([]byte, []int) {
	return file_chat_room_delete_service_proto_rawDescGZIP(), []int{0}
}

type DeleteChatRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *DeleteChatRoomRequest_ChatRoom `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *DeleteChatRoomRequest) Reset() {
	*x = DeleteChatRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_delete_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRoomRequest) ProtoMessage() {}

func (x *DeleteChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_delete_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_chat_room_delete_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteChatRoomRequest) GetRoom() *DeleteChatRoomRequest_ChatRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteChatRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *ChatRoom `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *DeleteChatRoomResponse) Reset() {
	*x = DeleteChatRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_delete_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChatRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRoomResponse) ProtoMessage() {}

func (x *DeleteChatRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_delete_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatRoomResponse) Descriptor() ([]byte, []int) {
	return file_chat_room_delete_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteChatRoomResponse) GetRoom() *ChatRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteChatRoomRequest_ChatRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteChatRoomRequest_ChatRoom) Reset() {
	*x = DeleteChatRoomRequest_ChatRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_delete_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChatRoomRequest_ChatRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRoomRequest_ChatRoom) ProtoMessage() {}

func (x *DeleteChatRoomRequest_ChatRoom) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_delete_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRoomRequest_ChatRoom.ProtoReflect.Descriptor instead.
func (*DeleteChatRoomRequest_ChatRoom) Descriptor() ([]byte, []int) {
	return file_chat_room_delete_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeleteChatRoomRequest_ChatRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_chat_room_delete_service_proto protoreflect.FileDescriptor

var file_chat_room_delete_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x72, 0x6f, 0x6f, 0x6d, 0x2d, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x38, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x1a, 0x1a, 0x0a, 0x08, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04,
	0x72, 0x6f, 0x6f, 0x6d, 0x2a, 0x46, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52,
	0x4f, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x4f,
	0x4f, 0x4d, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x01, 0x32, 0x64, 0x0a, 0x15,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1b, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x2d, 0x69, 0x64, 0x6c, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_room_delete_service_proto_rawDescOnce sync.Once
	file_chat_room_delete_service_proto_rawDescData = file_chat_room_delete_service_proto_rawDesc
)

func file_chat_room_delete_service_proto_rawDescGZIP() []byte {
	file_chat_room_delete_service_proto_rawDescOnce.Do(func() {
		file_chat_room_delete_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_room_delete_service_proto_rawDescData)
	})
	return file_chat_room_delete_service_proto_rawDescData
}

var file_chat_room_delete_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_room_delete_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chat_room_delete_service_proto_goTypes = []interface{}{
	(ChatRoomDeleteEventType)(0),           // 0: chat.ChatRoomDeleteEventType
	(*DeleteChatRoomRequest)(nil),          // 1: chat.DeleteChatRoomRequest
	(*DeleteChatRoomResponse)(nil),         // 2: chat.DeleteChatRoomResponse
	(*DeleteChatRoomRequest_ChatRoom)(nil), // 3: chat.DeleteChatRoomRequest.ChatRoom
	(*ChatRoom)(nil),                       // 4: chat.ChatRoom
}
var file_chat_room_delete_service_proto_depIdxs = []int32{
	3, // 0: chat.DeleteChatRoomRequest.room:type_name -> chat.DeleteChatRoomRequest.ChatRoom
	4, // 1: chat.DeleteChatRoomResponse.room:type_name -> chat.ChatRoom
	1, // 2: chat.ChatRoomDeleteService.DeleteChatRoom:input_type -> chat.DeleteChatRoomRequest
	2, // 3: chat.ChatRoomDeleteService.DeleteChatRoom:output_type -> chat.DeleteChatRoomResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_room_delete_service_proto_init() }
func file_chat_room_delete_service_proto_init() {
	if File_chat_room_delete_service_proto != nil {
		return
	}
	file_chat_room_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_room_delete_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChatRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_room_delete_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChatRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_room_delete_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChatRoomRequest_ChatRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_room_delete_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_room_delete_service_proto_goTypes,
		DependencyIndexes: file_chat_room_delete_service_proto_depIdxs,
		EnumInfos:         file_chat_room_delete_service_proto_enumTypes,
		MessageInfos:      file_chat_room_delete_service_proto_msgTypes,
	}.Build()
	File_chat_room_delete_service_proto = out.File
	file_chat_room_delete_service_proto_rawDesc = nil
	file_chat_room_delete_service_proto_goTypes = nil
	file_chat_room_delete_service_proto_depIdxs = nil
}
