// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: chat-user-create.service.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatUserCreateServiceClient is the client API for ChatUserCreateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatUserCreateServiceClient interface {
	CreateChatUser(ctx context.Context, in *CreateChatUserRequest, opts ...grpc.CallOption) (*CreateChatUserResponse, error)
}

type chatUserCreateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatUserCreateServiceClient(cc grpc.ClientConnInterface) ChatUserCreateServiceClient {
	return &chatUserCreateServiceClient{cc}
}

func (c *chatUserCreateServiceClient) CreateChatUser(ctx context.Context, in *CreateChatUserRequest, opts ...grpc.CallOption) (*CreateChatUserResponse, error) {
	out := new(CreateChatUserResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatUserCreateService/CreateChatUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatUserCreateServiceServer is the server API for ChatUserCreateService service.
// All implementations must embed UnimplementedChatUserCreateServiceServer
// for forward compatibility
type ChatUserCreateServiceServer interface {
	CreateChatUser(context.Context, *CreateChatUserRequest) (*CreateChatUserResponse, error)
	mustEmbedUnimplementedChatUserCreateServiceServer()
}

// UnimplementedChatUserCreateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatUserCreateServiceServer struct {
}

func (UnimplementedChatUserCreateServiceServer) CreateChatUser(context.Context, *CreateChatUserRequest) (*CreateChatUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatUser not implemented")
}
func (UnimplementedChatUserCreateServiceServer) mustEmbedUnimplementedChatUserCreateServiceServer() {}

// UnsafeChatUserCreateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatUserCreateServiceServer will
// result in compilation errors.
type UnsafeChatUserCreateServiceServer interface {
	mustEmbedUnimplementedChatUserCreateServiceServer()
}

func RegisterChatUserCreateServiceServer(s grpc.ServiceRegistrar, srv ChatUserCreateServiceServer) {
	s.RegisterService(&ChatUserCreateService_ServiceDesc, srv)
}

func _ChatUserCreateService_CreateChatUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatUserCreateServiceServer).CreateChatUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatUserCreateService/CreateChatUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatUserCreateServiceServer).CreateChatUser(ctx, req.(*CreateChatUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatUserCreateService_ServiceDesc is the grpc.ServiceDesc for ChatUserCreateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatUserCreateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatUserCreateService",
	HandlerType: (*ChatUserCreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatUser",
			Handler:    _ChatUserCreateService_CreateChatUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-user-create.service.proto",
}
