// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: chat-message-create.service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessageCreateEventType int32

const (
	ChatMessageCreateEventType_CREATE_CHAT_MESSAGE  ChatMessageCreateEventType = 0
	ChatMessageCreateEventType_CHAT_MESSAGE_CREATED ChatMessageCreateEventType = 1
)

// Enum value maps for ChatMessageCreateEventType.
var (
	ChatMessageCreateEventType_name = map[int32]string{
		0: "CREATE_CHAT_MESSAGE",
		1: "CHAT_MESSAGE_CREATED",
	}
	ChatMessageCreateEventType_value = map[string]int32{
		"CREATE_CHAT_MESSAGE":  0,
		"CHAT_MESSAGE_CREATED": 1,
	}
)

func (x ChatMessageCreateEventType) Enum() *ChatMessageCreateEventType {
	p := new(ChatMessageCreateEventType)
	*p = x
	return p
}

func (x ChatMessageCreateEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageCreateEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_message_create_service_proto_enumTypes[0].Descriptor()
}

func (ChatMessageCreateEventType) Type() protoreflect.EnumType {
	return &file_chat_message_create_service_proto_enumTypes[0]
}

func (x ChatMessageCreateEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageCreateEventType.Descriptor instead.
func (ChatMessageCreateEventType) EnumDescriptor() ([]byte, []int) {
	return file_chat_message_create_service_proto_rawDescGZIP(), []int{0}
}

type CreateChatMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *CreateChatMessageRequest_ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateChatMessageRequest) Reset() {
	*x = CreateChatMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_message_create_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageRequest) ProtoMessage() {}

func (x *CreateChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_message_create_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_message_create_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatMessageRequest) GetMessage() *CreateChatMessageRequest_ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type CreateChatMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateChatMessageResponse) Reset() {
	*x = CreateChatMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_message_create_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageResponse) ProtoMessage() {}

func (x *CreateChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_message_create_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_message_create_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type CreateChatMessageRequest_ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateChatMessageRequest_ChatMessage) Reset() {
	*x = CreateChatMessageRequest_ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_message_create_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatMessageRequest_ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageRequest_ChatMessage) ProtoMessage() {}

func (x *CreateChatMessageRequest_ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_message_create_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageRequest_ChatMessage.ProtoReflect.Descriptor instead.
func (*CreateChatMessageRequest_ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_message_create_service_proto_rawDescGZIP(), []int{0, 0}
}

type CreateChatMessageRequest_ChatMessage_ChatRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateChatMessageRequest_ChatMessage_ChatRoom) Reset() {
	*x = CreateChatMessageRequest_ChatMessage_ChatRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_message_create_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatMessageRequest_ChatMessage_ChatRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageRequest_ChatMessage_ChatRoom) ProtoMessage() {}

func (x *CreateChatMessageRequest_ChatMessage_ChatRoom) ProtoReflect() protoreflect.Message {
	mi := &file_chat_message_create_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageRequest_ChatMessage_ChatRoom.ProtoReflect.Descriptor instead.
func (*CreateChatMessageRequest_ChatMessage_ChatRoom) Descriptor() ([]byte, []int) {
	return file_chat_message_create_service_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateChatMessageRequest_ChatMessage_ChatRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_chat_message_create_service_proto protoreflect.FileDescriptor

var file_chat_message_create_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x12, 0x63, 0x68, 0x61, 0x74, 0x2d,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x29, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x19, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x4f, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48,
	0x41, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x32, 0x70, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c,
	0x6c, 0x2d, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68,
	0x65, 0x6c, 0x6c, 0x2d, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2d, 0x69, 0x64, 0x6c, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_message_create_service_proto_rawDescOnce sync.Once
	file_chat_message_create_service_proto_rawDescData = file_chat_message_create_service_proto_rawDesc
)

func file_chat_message_create_service_proto_rawDescGZIP() []byte {
	file_chat_message_create_service_proto_rawDescOnce.Do(func() {
		file_chat_message_create_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_message_create_service_proto_rawDescData)
	})
	return file_chat_message_create_service_proto_rawDescData
}

var file_chat_message_create_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_message_create_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chat_message_create_service_proto_goTypes = []interface{}{
	(ChatMessageCreateEventType)(0),                       // 0: chat.ChatMessageCreateEventType
	(*CreateChatMessageRequest)(nil),                      // 1: chat.CreateChatMessageRequest
	(*CreateChatMessageResponse)(nil),                     // 2: chat.CreateChatMessageResponse
	(*CreateChatMessageRequest_ChatMessage)(nil),          // 3: chat.CreateChatMessageRequest.ChatMessage
	(*CreateChatMessageRequest_ChatMessage_ChatRoom)(nil), // 4: chat.CreateChatMessageRequest.ChatMessage.ChatRoom
	(*ChatMessage)(nil),                                   // 5: chat.ChatMessage
}
var file_chat_message_create_service_proto_depIdxs = []int32{
	3, // 0: chat.CreateChatMessageRequest.message:type_name -> chat.CreateChatMessageRequest.ChatMessage
	5, // 1: chat.CreateChatMessageResponse.message:type_name -> chat.ChatMessage
	1, // 2: chat.ChatMessageCreateService.CreateChatMessage:input_type -> chat.CreateChatMessageRequest
	2, // 3: chat.ChatMessageCreateService.CreateChatMessage:output_type -> chat.CreateChatMessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_message_create_service_proto_init() }
func file_chat_message_create_service_proto_init() {
	if File_chat_message_create_service_proto != nil {
		return
	}
	file_chat_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_message_create_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_message_create_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_message_create_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatMessageRequest_ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_message_create_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatMessageRequest_ChatMessage_ChatRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_message_create_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_message_create_service_proto_goTypes,
		DependencyIndexes: file_chat_message_create_service_proto_depIdxs,
		EnumInfos:         file_chat_message_create_service_proto_enumTypes,
		MessageInfos:      file_chat_message_create_service_proto_msgTypes,
	}.Build()
	File_chat_message_create_service_proto = out.File
	file_chat_message_create_service_proto_rawDesc = nil
	file_chat_message_create_service_proto_goTypes = nil
	file_chat_message_create_service_proto_depIdxs = nil
}
