// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: chat-participant-create.service.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatParticipantCreateServiceClient is the client API for ChatParticipantCreateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatParticipantCreateServiceClient interface {
	CreateChatParticipant(ctx context.Context, in *CreateChatParticipantRequest, opts ...grpc.CallOption) (*CreateChatParticipantResponse, error)
}

type chatParticipantCreateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatParticipantCreateServiceClient(cc grpc.ClientConnInterface) ChatParticipantCreateServiceClient {
	return &chatParticipantCreateServiceClient{cc}
}

func (c *chatParticipantCreateServiceClient) CreateChatParticipant(ctx context.Context, in *CreateChatParticipantRequest, opts ...grpc.CallOption) (*CreateChatParticipantResponse, error) {
	out := new(CreateChatParticipantResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatParticipantCreateService/CreateChatParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatParticipantCreateServiceServer is the server API for ChatParticipantCreateService service.
// All implementations must embed UnimplementedChatParticipantCreateServiceServer
// for forward compatibility
type ChatParticipantCreateServiceServer interface {
	CreateChatParticipant(context.Context, *CreateChatParticipantRequest) (*CreateChatParticipantResponse, error)
	mustEmbedUnimplementedChatParticipantCreateServiceServer()
}

// UnimplementedChatParticipantCreateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatParticipantCreateServiceServer struct {
}

func (UnimplementedChatParticipantCreateServiceServer) CreateChatParticipant(context.Context, *CreateChatParticipantRequest) (*CreateChatParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatParticipant not implemented")
}
func (UnimplementedChatParticipantCreateServiceServer) mustEmbedUnimplementedChatParticipantCreateServiceServer() {
}

// UnsafeChatParticipantCreateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatParticipantCreateServiceServer will
// result in compilation errors.
type UnsafeChatParticipantCreateServiceServer interface {
	mustEmbedUnimplementedChatParticipantCreateServiceServer()
}

func RegisterChatParticipantCreateServiceServer(s grpc.ServiceRegistrar, srv ChatParticipantCreateServiceServer) {
	s.RegisterService(&ChatParticipantCreateService_ServiceDesc, srv)
}

func _ChatParticipantCreateService_CreateChatParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatParticipantCreateServiceServer).CreateChatParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatParticipantCreateService/CreateChatParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatParticipantCreateServiceServer).CreateChatParticipant(ctx, req.(*CreateChatParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatParticipantCreateService_ServiceDesc is the grpc.ServiceDesc for ChatParticipantCreateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatParticipantCreateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatParticipantCreateService",
	HandlerType: (*ChatParticipantCreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatParticipant",
			Handler:    _ChatParticipantCreateService_CreateChatParticipant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-participant-create.service.proto",
}
