// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: chat-room-read-list.service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRoomReadListEventType int32

const (
	ChatRoomReadListEventType_READ_LIST_CHAT_ROOM ChatRoomReadListEventType = 0
	ChatRoomReadListEventType_CHAT_ROOM_READ_LIST ChatRoomReadListEventType = 1
)

// Enum value maps for ChatRoomReadListEventType.
var (
	ChatRoomReadListEventType_name = map[int32]string{
		0: "READ_LIST_CHAT_ROOM",
		1: "CHAT_ROOM_READ_LIST",
	}
	ChatRoomReadListEventType_value = map[string]int32{
		"READ_LIST_CHAT_ROOM": 0,
		"CHAT_ROOM_READ_LIST": 1,
	}
)

func (x ChatRoomReadListEventType) Enum() *ChatRoomReadListEventType {
	p := new(ChatRoomReadListEventType)
	*p = x
	return p
}

func (x ChatRoomReadListEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRoomReadListEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_room_read_list_service_proto_enumTypes[0].Descriptor()
}

func (ChatRoomReadListEventType) Type() protoreflect.EnumType {
	return &file_chat_room_read_list_service_proto_enumTypes[0]
}

func (x ChatRoomReadListEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRoomReadListEventType.Descriptor instead.
func (ChatRoomReadListEventType) EnumDescriptor() ([]byte, []int) {
	return file_chat_room_read_list_service_proto_rawDescGZIP(), []int{0}
}

type ReadListChatRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room        *ReadListChatRoomRequest_ChatRoomCondition        `protobuf:"bytes,1,opt,name=room,proto3,oneof" json:"room,omitempty"`
	Participant *ReadListChatRoomRequest_ChatParticipantCondition `protobuf:"bytes,2,opt,name=participant,proto3,oneof" json:"participant,omitempty"`
}

func (x *ReadListChatRoomRequest) Reset() {
	*x = ReadListChatRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_read_list_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadListChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadListChatRoomRequest) ProtoMessage() {}

func (x *ReadListChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_read_list_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadListChatRoomRequest.ProtoReflect.Descriptor instead.
func (*ReadListChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_chat_room_read_list_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReadListChatRoomRequest) GetRoom() *ReadListChatRoomRequest_ChatRoomCondition {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *ReadListChatRoomRequest) GetParticipant() *ReadListChatRoomRequest_ChatParticipantCondition {
	if x != nil {
		return x.Participant
	}
	return nil
}

type ReadListChatRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ChatRoom `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ReadListChatRoomResponse) Reset() {
	*x = ReadListChatRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_read_list_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadListChatRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadListChatRoomResponse) ProtoMessage() {}

func (x *ReadListChatRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_read_list_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadListChatRoomResponse.ProtoReflect.Descriptor instead.
func (*ReadListChatRoomResponse) Descriptor() ([]byte, []int) {
	return file_chat_room_read_list_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReadListChatRoomResponse) GetResults() []*ChatRoom {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadListChatRoomRequest_ChatRoomCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids                 []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	CreatedDateTimeFrom *string  `protobuf:"bytes,2,opt,name=createdDateTimeFrom,proto3,oneof" json:"createdDateTimeFrom,omitempty"`
	CreatedDateTimeTo   *string  `protobuf:"bytes,3,opt,name=createdDateTimeTo,proto3,oneof" json:"createdDateTimeTo,omitempty"`
}

func (x *ReadListChatRoomRequest_ChatRoomCondition) Reset() {
	*x = ReadListChatRoomRequest_ChatRoomCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_read_list_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadListChatRoomRequest_ChatRoomCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadListChatRoomRequest_ChatRoomCondition) ProtoMessage() {}

func (x *ReadListChatRoomRequest_ChatRoomCondition) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_read_list_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadListChatRoomRequest_ChatRoomCondition.ProtoReflect.Descriptor instead.
func (*ReadListChatRoomRequest_ChatRoomCondition) Descriptor() ([]byte, []int) {
	return file_chat_room_read_list_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReadListChatRoomRequest_ChatRoomCondition) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ReadListChatRoomRequest_ChatRoomCondition) GetCreatedDateTimeFrom() string {
	if x != nil && x.CreatedDateTimeFrom != nil {
		return *x.CreatedDateTimeFrom
	}
	return ""
}

func (x *ReadListChatRoomRequest_ChatRoomCondition) GetCreatedDateTimeTo() string {
	if x != nil && x.CreatedDateTimeTo != nil {
		return *x.CreatedDateTimeTo
	}
	return ""
}

type ReadListChatRoomRequest_ChatParticipantCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids                 []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	CreatedDateTimeFrom *string  `protobuf:"bytes,2,opt,name=createdDateTimeFrom,proto3,oneof" json:"createdDateTimeFrom,omitempty"`
	CreatedDateTimeTo   *string  `protobuf:"bytes,3,opt,name=createdDateTimeTo,proto3,oneof" json:"createdDateTimeTo,omitempty"`
}

func (x *ReadListChatRoomRequest_ChatParticipantCondition) Reset() {
	*x = ReadListChatRoomRequest_ChatParticipantCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_room_read_list_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadListChatRoomRequest_ChatParticipantCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadListChatRoomRequest_ChatParticipantCondition) ProtoMessage() {}

func (x *ReadListChatRoomRequest_ChatParticipantCondition) ProtoReflect() protoreflect.Message {
	mi := &file_chat_room_read_list_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadListChatRoomRequest_ChatParticipantCondition.ProtoReflect.Descriptor instead.
func (*ReadListChatRoomRequest_ChatParticipantCondition) Descriptor() ([]byte, []int) {
	return file_chat_room_read_list_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ReadListChatRoomRequest_ChatParticipantCondition) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ReadListChatRoomRequest_ChatParticipantCondition) GetCreatedDateTimeFrom() string {
	if x != nil && x.CreatedDateTimeFrom != nil {
		return *x.CreatedDateTimeFrom
	}
	return ""
}

func (x *ReadListChatRoomRequest_ChatParticipantCondition) GetCreatedDateTimeTo() string {
	if x != nil && x.CreatedDateTimeTo != nil {
		return *x.CreatedDateTimeTo
	}
	return ""
}

var File_chat_room_read_list_service_proto protoreflect.FileDescriptor

var file_chat_room_read_list_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x72, 0x6f, 0x6f, 0x6d, 0x2d, 0x72, 0x65, 0x61, 0x64,
	0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x2d,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x04, 0x0a, 0x17, 0x52,
	0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x88, 0x01, 0x01,
	0x12, 0x5d, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69,
	0x70, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52,
	0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x1a,
	0xbd, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x31,
	0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x11, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x88, 0x01,
	0x01, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x1a,
	0xc4, 0x01, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x35,
	0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x13, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x54, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x42, 0x14, 0x0a, 0x12, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x22,
	0x44, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x2a, 0x4d, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43,
	0x48, 0x41, 0x54, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x01, 0x32, 0x6c, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x51, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x1d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x2d, 0x69, 0x64, 0x6c, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_room_read_list_service_proto_rawDescOnce sync.Once
	file_chat_room_read_list_service_proto_rawDescData = file_chat_room_read_list_service_proto_rawDesc
)

func file_chat_room_read_list_service_proto_rawDescGZIP() []byte {
	file_chat_room_read_list_service_proto_rawDescOnce.Do(func() {
		file_chat_room_read_list_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_room_read_list_service_proto_rawDescData)
	})
	return file_chat_room_read_list_service_proto_rawDescData
}

var file_chat_room_read_list_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_room_read_list_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chat_room_read_list_service_proto_goTypes = []interface{}{
	(ChatRoomReadListEventType)(0),                           // 0: chat.ChatRoomReadListEventType
	(*ReadListChatRoomRequest)(nil),                          // 1: chat.ReadListChatRoomRequest
	(*ReadListChatRoomResponse)(nil),                         // 2: chat.ReadListChatRoomResponse
	(*ReadListChatRoomRequest_ChatRoomCondition)(nil),        // 3: chat.ReadListChatRoomRequest.ChatRoomCondition
	(*ReadListChatRoomRequest_ChatParticipantCondition)(nil), // 4: chat.ReadListChatRoomRequest.ChatParticipantCondition
	(*ChatRoom)(nil),                                         // 5: chat.ChatRoom
}
var file_chat_room_read_list_service_proto_depIdxs = []int32{
	3, // 0: chat.ReadListChatRoomRequest.room:type_name -> chat.ReadListChatRoomRequest.ChatRoomCondition
	4, // 1: chat.ReadListChatRoomRequest.participant:type_name -> chat.ReadListChatRoomRequest.ChatParticipantCondition
	5, // 2: chat.ReadListChatRoomResponse.results:type_name -> chat.ChatRoom
	1, // 3: chat.ChatRoomReadListService.ReadListChatRoom:input_type -> chat.ReadListChatRoomRequest
	2, // 4: chat.ChatRoomReadListService.ReadListChatRoom:output_type -> chat.ReadListChatRoomResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chat_room_read_list_service_proto_init() }
func file_chat_room_read_list_service_proto_init() {
	if File_chat_room_read_list_service_proto != nil {
		return
	}
	file_chat_room_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_room_read_list_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadListChatRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_room_read_list_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadListChatRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_room_read_list_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadListChatRoomRequest_ChatRoomCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_room_read_list_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadListChatRoomRequest_ChatParticipantCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chat_room_read_list_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_chat_room_read_list_service_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_chat_room_read_list_service_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_room_read_list_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_room_read_list_service_proto_goTypes,
		DependencyIndexes: file_chat_room_read_list_service_proto_depIdxs,
		EnumInfos:         file_chat_room_read_list_service_proto_enumTypes,
		MessageInfos:      file_chat_room_read_list_service_proto_msgTypes,
	}.Build()
	File_chat_room_read_list_service_proto = out.File
	file_chat_room_read_list_service_proto_rawDesc = nil
	file_chat_room_read_list_service_proto_goTypes = nil
	file_chat_room_read_list_service_proto_depIdxs = nil
}
