// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: place.service.proto

package place

import (
	place "github.com/knighthell/knighthell-boilerplate-idl-proto/place"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryPlaceListBySquareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopRightLatitude    float64  `protobuf:"fixed64,1,opt,name=topRightLatitude,proto3" json:"topRightLatitude,omitempty"`
	TopRightLongitude   float64  `protobuf:"fixed64,2,opt,name=topRightLongitude,proto3" json:"topRightLongitude,omitempty"`
	BottomLeftLatitude  float64  `protobuf:"fixed64,3,opt,name=bottomLeftLatitude,proto3" json:"bottomLeftLatitude,omitempty"`
	BottomLeftLongitude float64  `protobuf:"fixed64,4,opt,name=bottomLeftLongitude,proto3" json:"bottomLeftLongitude,omitempty"`
	UserLatitude        *float64 `protobuf:"fixed64,5,opt,name=userLatitude,proto3,oneof" json:"userLatitude,omitempty"`
	UserLongitude       *float64 `protobuf:"fixed64,6,opt,name=userLongitude,proto3,oneof" json:"userLongitude,omitempty"`
}

func (x *QueryPlaceListBySquareRequest) Reset() {
	*x = QueryPlaceListBySquareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlaceListBySquareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlaceListBySquareRequest) ProtoMessage() {}

func (x *QueryPlaceListBySquareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlaceListBySquareRequest.ProtoReflect.Descriptor instead.
func (*QueryPlaceListBySquareRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPlaceListBySquareRequest) GetTopRightLatitude() float64 {
	if x != nil {
		return x.TopRightLatitude
	}
	return 0
}

func (x *QueryPlaceListBySquareRequest) GetTopRightLongitude() float64 {
	if x != nil {
		return x.TopRightLongitude
	}
	return 0
}

func (x *QueryPlaceListBySquareRequest) GetBottomLeftLatitude() float64 {
	if x != nil {
		return x.BottomLeftLatitude
	}
	return 0
}

func (x *QueryPlaceListBySquareRequest) GetBottomLeftLongitude() float64 {
	if x != nil {
		return x.BottomLeftLongitude
	}
	return 0
}

func (x *QueryPlaceListBySquareRequest) GetUserLatitude() float64 {
	if x != nil && x.UserLatitude != nil {
		return *x.UserLatitude
	}
	return 0
}

func (x *QueryPlaceListBySquareRequest) GetUserLongitude() float64 {
	if x != nil && x.UserLongitude != nil {
		return *x.UserLongitude
	}
	return 0
}

type QueryPlaceListBySquareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*place.Place `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *QueryPlaceListBySquareResponse) Reset() {
	*x = QueryPlaceListBySquareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlaceListBySquareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlaceListBySquareResponse) ProtoMessage() {}

func (x *QueryPlaceListBySquareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlaceListBySquareResponse.ProtoReflect.Descriptor instead.
func (*QueryPlaceListBySquareResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryPlaceListBySquareResponse) GetResults() []*place.Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type QueryPlaceListByRadiusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterLatitude  float64  `protobuf:"fixed64,1,opt,name=centerLatitude,proto3" json:"centerLatitude,omitempty"`
	CenterLongitude float64  `protobuf:"fixed64,2,opt,name=centerLongitude,proto3" json:"centerLongitude,omitempty"`
	MeterRadius     uint32   `protobuf:"varint,3,opt,name=meterRadius,proto3" json:"meterRadius,omitempty"`
	UserLatitude    *float64 `protobuf:"fixed64,4,opt,name=userLatitude,proto3,oneof" json:"userLatitude,omitempty"`
	UserLongitude   *float64 `protobuf:"fixed64,5,opt,name=userLongitude,proto3,oneof" json:"userLongitude,omitempty"`
}

func (x *QueryPlaceListByRadiusRequest) Reset() {
	*x = QueryPlaceListByRadiusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlaceListByRadiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlaceListByRadiusRequest) ProtoMessage() {}

func (x *QueryPlaceListByRadiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlaceListByRadiusRequest.ProtoReflect.Descriptor instead.
func (*QueryPlaceListByRadiusRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPlaceListByRadiusRequest) GetCenterLatitude() float64 {
	if x != nil {
		return x.CenterLatitude
	}
	return 0
}

func (x *QueryPlaceListByRadiusRequest) GetCenterLongitude() float64 {
	if x != nil {
		return x.CenterLongitude
	}
	return 0
}

func (x *QueryPlaceListByRadiusRequest) GetMeterRadius() uint32 {
	if x != nil {
		return x.MeterRadius
	}
	return 0
}

func (x *QueryPlaceListByRadiusRequest) GetUserLatitude() float64 {
	if x != nil && x.UserLatitude != nil {
		return *x.UserLatitude
	}
	return 0
}

func (x *QueryPlaceListByRadiusRequest) GetUserLongitude() float64 {
	if x != nil && x.UserLongitude != nil {
		return *x.UserLongitude
	}
	return 0
}

type QueryPlaceListByRadiusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*place.Place `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *QueryPlaceListByRadiusResponse) Reset() {
	*x = QueryPlaceListByRadiusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlaceListByRadiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlaceListByRadiusResponse) ProtoMessage() {}

func (x *QueryPlaceListByRadiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlaceListByRadiusResponse.ProtoReflect.Descriptor instead.
func (*QueryPlaceListByRadiusResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPlaceListByRadiusResponse) GetResults() []*place.Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreatePlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *CreatePlaceRequest) Reset() {
	*x = CreatePlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceRequest) ProtoMessage() {}

func (x *CreatePlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaceRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePlaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlaceRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePlaceRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ReadPlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadPlaceRequest) Reset() {
	*x = ReadPlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceRequest) ProtoMessage() {}

func (x *ReadPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceRequest.ProtoReflect.Descriptor instead.
func (*ReadPlaceRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadPlaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadPlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place *place.Place `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
}

func (x *ReadPlaceResponse) Reset() {
	*x = ReadPlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceResponse) ProtoMessage() {}

func (x *ReadPlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceResponse.ProtoReflect.Descriptor instead.
func (*ReadPlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadPlaceResponse) GetPlace() *place.Place {
	if x != nil {
		return x.Place
	}
	return nil
}

type ReadPlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*ReadPlaceRequest `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *ReadPlaceListRequest) Reset() {
	*x = ReadPlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceListRequest) ProtoMessage() {}

func (x *ReadPlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceListRequest.ProtoReflect.Descriptor instead.
func (*ReadPlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadPlaceListRequest) GetPlaces() []*ReadPlaceRequest {
	if x != nil {
		return x.Places
	}
	return nil
}

type ReadPlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*place.Place `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *ReadPlaceListResponse) Reset() {
	*x = ReadPlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceListResponse) ProtoMessage() {}

func (x *ReadPlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceListResponse.ProtoReflect.Descriptor instead.
func (*ReadPlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadPlaceListResponse) GetPlaces() []*place.Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type CreatePlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place *place.Place `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
}

func (x *CreatePlaceResponse) Reset() {
	*x = CreatePlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceResponse) ProtoMessage() {}

func (x *CreatePlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePlaceResponse) GetPlace() *place.Place {
	if x != nil {
		return x.Place
	}
	return nil
}

type CreatePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*CreatePlaceRequest `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *CreatePlaceListRequest) Reset() {
	*x = CreatePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListRequest) ProtoMessage() {}

func (x *CreatePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePlaceListRequest) GetPlaces() []*CreatePlaceRequest {
	if x != nil {
		return x.Places
	}
	return nil
}

type CreatePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*place.Place `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *CreatePlaceListResponse) Reset() {
	*x = CreatePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListResponse) ProtoMessage() {}

func (x *CreatePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePlaceListResponse) GetPlaces() []*place.Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type UpdatePlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      *string  `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Latitude  *float64 `protobuf:"fixed64,2,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude *float64 `protobuf:"fixed64,3,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
}

func (x *UpdatePlaceRequest) Reset() {
	*x = UpdatePlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceRequest) ProtoMessage() {}

func (x *UpdatePlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaceRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePlaceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePlaceRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdatePlaceRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type UpdatePlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place *place.Place `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
}

func (x *UpdatePlaceResponse) Reset() {
	*x = UpdatePlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceResponse) ProtoMessage() {}

func (x *UpdatePlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePlaceResponse) GetPlace() *place.Place {
	if x != nil {
		return x.Place
	}
	return nil
}

type UpdatePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*UpdatePlaceRequest `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *UpdatePlaceListRequest) Reset() {
	*x = UpdatePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceListRequest) ProtoMessage() {}

func (x *UpdatePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceListRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePlaceListRequest) GetPlaces() []*UpdatePlaceRequest {
	if x != nil {
		return x.Places
	}
	return nil
}

type UpdatePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*place.Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *UpdatePlaceListResponse) Reset() {
	*x = UpdatePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceListResponse) ProtoMessage() {}

func (x *UpdatePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceListResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePlaceListResponse) GetPlaces() []*place.Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type DeletePlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePlaceRequest) Reset() {
	*x = DeletePlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceRequest) ProtoMessage() {}

func (x *DeletePlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceRequest.ProtoReflect.Descriptor instead.
func (*DeletePlaceRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePlaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place *place.Place `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
}

func (x *DeletePlaceResponse) Reset() {
	*x = DeletePlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceResponse) ProtoMessage() {}

func (x *DeletePlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceResponse.ProtoReflect.Descriptor instead.
func (*DeletePlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePlaceResponse) GetPlace() *place.Place {
	if x != nil {
		return x.Place
	}
	return nil
}

type DeletePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*DeletePlaceRequest `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *DeletePlaceListRequest) Reset() {
	*x = DeletePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceListRequest) ProtoMessage() {}

func (x *DeletePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceListRequest.ProtoReflect.Descriptor instead.
func (*DeletePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePlaceListRequest) GetPlaces() []*DeletePlaceRequest {
	if x != nil {
		return x.Places
	}
	return nil
}

type DeletePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*place.Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *DeletePlaceListResponse) Reset() {
	*x = DeletePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceListResponse) ProtoMessage() {}

func (x *DeletePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceListResponse.ProtoReflect.Descriptor instead.
func (*DeletePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePlaceListResponse) GetPlaces() []*place.Place {
	if x != nil {
		return x.Places
	}
	return nil
}

var File_place_service_proto protoreflect.FileDescriptor

var file_place_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x1a, 0x0b, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x02, 0x0a, 0x1d, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x74,
	0x6f, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x74, 0x6f, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x4c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x74, 0x6f, 0x70, 0x52, 0x69,
	0x67, 0x68, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x11, 0x74, 0x6f, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x4c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c,
	0x65, 0x66, 0x74, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x12, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c,
	0x65, 0x66, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x13, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x4c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x29, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x10, 0x0a, 0x0e,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x48,
	0x0a, 0x1e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x8a, 0x02, 0x0a, 0x1d, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x52, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0e, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x27,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01,
	0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x48, 0x0a, 0x1e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0x62, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x22, 0x47, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x15, 0x52, 0x65, 0x61,
	0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x05, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x22, 0x3f, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x05, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x22, 0x3f, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x05, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x22, 0x3f, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x32, 0xb0, 0x06, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x65, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12, 0x24, 0x2e, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x16, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x52, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x52, 0x61, 0x64, 0x69,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12,
	0x19, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2d, 0x69, 0x64, 0x6c, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_place_service_proto_rawDescOnce sync.Once
	file_place_service_proto_rawDescData = file_place_service_proto_rawDesc
)

func file_place_service_proto_rawDescGZIP() []byte {
	file_place_service_proto_rawDescOnce.Do(func() {
		file_place_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_service_proto_rawDescData)
	})
	return file_place_service_proto_rawDescData
}

var file_place_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_place_service_proto_goTypes = []interface{}{
	(*QueryPlaceListBySquareRequest)(nil),  // 0: place.QueryPlaceListBySquareRequest
	(*QueryPlaceListBySquareResponse)(nil), // 1: place.QueryPlaceListBySquareResponse
	(*QueryPlaceListByRadiusRequest)(nil),  // 2: place.QueryPlaceListByRadiusRequest
	(*QueryPlaceListByRadiusResponse)(nil), // 3: place.QueryPlaceListByRadiusResponse
	(*CreatePlaceRequest)(nil),             // 4: place.CreatePlaceRequest
	(*ReadPlaceRequest)(nil),               // 5: place.ReadPlaceRequest
	(*ReadPlaceResponse)(nil),              // 6: place.ReadPlaceResponse
	(*ReadPlaceListRequest)(nil),           // 7: place.ReadPlaceListRequest
	(*ReadPlaceListResponse)(nil),          // 8: place.ReadPlaceListResponse
	(*CreatePlaceResponse)(nil),            // 9: place.CreatePlaceResponse
	(*CreatePlaceListRequest)(nil),         // 10: place.CreatePlaceListRequest
	(*CreatePlaceListResponse)(nil),        // 11: place.CreatePlaceListResponse
	(*UpdatePlaceRequest)(nil),             // 12: place.UpdatePlaceRequest
	(*UpdatePlaceResponse)(nil),            // 13: place.UpdatePlaceResponse
	(*UpdatePlaceListRequest)(nil),         // 14: place.UpdatePlaceListRequest
	(*UpdatePlaceListResponse)(nil),        // 15: place.UpdatePlaceListResponse
	(*DeletePlaceRequest)(nil),             // 16: place.DeletePlaceRequest
	(*DeletePlaceResponse)(nil),            // 17: place.DeletePlaceResponse
	(*DeletePlaceListRequest)(nil),         // 18: place.DeletePlaceListRequest
	(*DeletePlaceListResponse)(nil),        // 19: place.DeletePlaceListResponse
	(*place.Place)(nil),                    // 20: place.Place
}
var file_place_service_proto_depIdxs = []int32{
	20, // 0: place.QueryPlaceListBySquareResponse.results:type_name -> place.Place
	20, // 1: place.QueryPlaceListByRadiusResponse.results:type_name -> place.Place
	20, // 2: place.ReadPlaceResponse.place:type_name -> place.Place
	5,  // 3: place.ReadPlaceListRequest.places:type_name -> place.ReadPlaceRequest
	20, // 4: place.ReadPlaceListResponse.places:type_name -> place.Place
	20, // 5: place.CreatePlaceResponse.place:type_name -> place.Place
	4,  // 6: place.CreatePlaceListRequest.places:type_name -> place.CreatePlaceRequest
	20, // 7: place.CreatePlaceListResponse.places:type_name -> place.Place
	20, // 8: place.UpdatePlaceResponse.place:type_name -> place.Place
	12, // 9: place.UpdatePlaceListRequest.places:type_name -> place.UpdatePlaceRequest
	20, // 10: place.UpdatePlaceListResponse.places:type_name -> place.Place
	20, // 11: place.DeletePlaceResponse.place:type_name -> place.Place
	16, // 12: place.DeletePlaceListRequest.places:type_name -> place.DeletePlaceRequest
	20, // 13: place.DeletePlaceListResponse.places:type_name -> place.Place
	0,  // 14: place.PlaceService.QueryPlaceListBySquare:input_type -> place.QueryPlaceListBySquareRequest
	2,  // 15: place.PlaceService.QueryPlaceListByRadius:input_type -> place.QueryPlaceListByRadiusRequest
	4,  // 16: place.PlaceService.CreatePlace:input_type -> place.CreatePlaceRequest
	10, // 17: place.PlaceService.CreatePlaceList:input_type -> place.CreatePlaceListRequest
	5,  // 18: place.PlaceService.ReadPlace:input_type -> place.ReadPlaceRequest
	7,  // 19: place.PlaceService.ReadPlaceList:input_type -> place.ReadPlaceListRequest
	12, // 20: place.PlaceService.UpdatePlace:input_type -> place.UpdatePlaceRequest
	14, // 21: place.PlaceService.UpdatePlaceList:input_type -> place.UpdatePlaceListRequest
	16, // 22: place.PlaceService.DeletePlace:input_type -> place.DeletePlaceRequest
	18, // 23: place.PlaceService.DeletePlaceList:input_type -> place.DeletePlaceListRequest
	1,  // 24: place.PlaceService.QueryPlaceListBySquare:output_type -> place.QueryPlaceListBySquareResponse
	3,  // 25: place.PlaceService.QueryPlaceListByRadius:output_type -> place.QueryPlaceListByRadiusResponse
	9,  // 26: place.PlaceService.CreatePlace:output_type -> place.CreatePlaceResponse
	11, // 27: place.PlaceService.CreatePlaceList:output_type -> place.CreatePlaceListResponse
	6,  // 28: place.PlaceService.ReadPlace:output_type -> place.ReadPlaceResponse
	8,  // 29: place.PlaceService.ReadPlaceList:output_type -> place.ReadPlaceListResponse
	13, // 30: place.PlaceService.UpdatePlace:output_type -> place.UpdatePlaceResponse
	15, // 31: place.PlaceService.UpdatePlaceList:output_type -> place.UpdatePlaceListResponse
	17, // 32: place.PlaceService.DeletePlace:output_type -> place.DeletePlaceResponse
	19, // 33: place.PlaceService.DeletePlaceList:output_type -> place.DeletePlaceListResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_place_service_proto_init() }
func file_place_service_proto_init() {
	if File_place_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPlaceListBySquareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPlaceListBySquareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPlaceListByRadiusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPlaceListByRadiusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_place_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_place_service_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_place_service_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_place_service_proto_goTypes,
		DependencyIndexes: file_place_service_proto_depIdxs,
		MessageInfos:      file_place_service_proto_msgTypes,
	}.Build()
	File_place_service_proto = out.File
	file_place_service_proto_rawDesc = nil
	file_place_service_proto_goTypes = nil
	file_place_service_proto_depIdxs = nil
}
