// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: place-read.service.proto

package place

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlaceReadServiceClient is the client API for PlaceReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaceReadServiceClient interface {
	ReadPlaceList(ctx context.Context, in *ReadPlaceListRequest, opts ...grpc.CallOption) (*ReadPlaceListResponse, error)
}

type placeReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaceReadServiceClient(cc grpc.ClientConnInterface) PlaceReadServiceClient {
	return &placeReadServiceClient{cc}
}

func (c *placeReadServiceClient) ReadPlaceList(ctx context.Context, in *ReadPlaceListRequest, opts ...grpc.CallOption) (*ReadPlaceListResponse, error) {
	out := new(ReadPlaceListResponse)
	err := c.cc.Invoke(ctx, "/place.service.read.PlaceReadService/ReadPlaceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceReadServiceServer is the server API for PlaceReadService service.
// All implementations must embed UnimplementedPlaceReadServiceServer
// for forward compatibility
type PlaceReadServiceServer interface {
	ReadPlaceList(context.Context, *ReadPlaceListRequest) (*ReadPlaceListResponse, error)
	mustEmbedUnimplementedPlaceReadServiceServer()
}

// UnimplementedPlaceReadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlaceReadServiceServer struct {
}

func (UnimplementedPlaceReadServiceServer) ReadPlaceList(context.Context, *ReadPlaceListRequest) (*ReadPlaceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPlaceList not implemented")
}
func (UnimplementedPlaceReadServiceServer) mustEmbedUnimplementedPlaceReadServiceServer() {}

// UnsafePlaceReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaceReadServiceServer will
// result in compilation errors.
type UnsafePlaceReadServiceServer interface {
	mustEmbedUnimplementedPlaceReadServiceServer()
}

func RegisterPlaceReadServiceServer(s grpc.ServiceRegistrar, srv PlaceReadServiceServer) {
	s.RegisterService(&PlaceReadService_ServiceDesc, srv)
}

func _PlaceReadService_ReadPlaceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPlaceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceReadServiceServer).ReadPlaceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.service.read.PlaceReadService/ReadPlaceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceReadServiceServer).ReadPlaceList(ctx, req.(*ReadPlaceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaceReadService_ServiceDesc is the grpc.ServiceDesc for PlaceReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaceReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "place.service.read.PlaceReadService",
	HandlerType: (*PlaceReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPlaceList",
			Handler:    _PlaceReadService_ReadPlaceList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "place-read.service.proto",
}
