// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: place-create.service.proto

package place

import (
	place "github.com/knighthell/knighthell-boilerplate-idl-proto/place"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceCreateServiceEventType int32

const (
	PlaceCreateServiceEventType_CREATE_PLACE PlaceCreateServiceEventType = 0
)

// Enum value maps for PlaceCreateServiceEventType.
var (
	PlaceCreateServiceEventType_name = map[int32]string{
		0: "CREATE_PLACE",
	}
	PlaceCreateServiceEventType_value = map[string]int32{
		"CREATE_PLACE": 0,
	}
)

func (x PlaceCreateServiceEventType) Enum() *PlaceCreateServiceEventType {
	p := new(PlaceCreateServiceEventType)
	*p = x
	return p
}

func (x PlaceCreateServiceEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaceCreateServiceEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_place_create_service_proto_enumTypes[0].Descriptor()
}

func (PlaceCreateServiceEventType) Type() protoreflect.EnumType {
	return &file_place_create_service_proto_enumTypes[0]
}

func (x PlaceCreateServiceEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaceCreateServiceEventType.Descriptor instead.
func (PlaceCreateServiceEventType) EnumDescriptor() ([]byte, []int) {
	return file_place_create_service_proto_rawDescGZIP(), []int{0}
}

type CreatePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*CreatePlaceListRequest_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *CreatePlaceListRequest) Reset() {
	*x = CreatePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_create_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListRequest) ProtoMessage() {}

func (x *CreatePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_create_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_create_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePlaceListRequest) GetPlaces() []*CreatePlaceListRequest_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type CreatePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*place.Place `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CreatePlaceListResponse) Reset() {
	*x = CreatePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_create_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListResponse) ProtoMessage() {}

func (x *CreatePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_create_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_create_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlaceListResponse) GetResults() []*place.Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreatePlaceListRequest_Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // 장소(Place)의 원래 이름
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`   // 장소(Place)의 위도
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"` // 장소(Place)의 경도
}

func (x *CreatePlaceListRequest_Place) Reset() {
	*x = CreatePlaceListRequest_Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_create_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListRequest_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListRequest_Place) ProtoMessage() {}

func (x *CreatePlaceListRequest_Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_create_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListRequest_Place.ProtoReflect.Descriptor instead.
func (*CreatePlaceListRequest_Place) Descriptor() ([]byte, []int) {
	return file_place_create_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreatePlaceListRequest_Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlaceListRequest_Place) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePlaceListRequest_Place) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_place_create_service_proto protoreflect.FileDescriptor

var file_place_create_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x1a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbb, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x55, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x41, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x2a, 0x2f, 0x0a, 0x1b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10,
	0x00, 0x32, 0x84, 0x01, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c,
	0x6c, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x62, 0x6f, 0x69,
	0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2d, 0x69, 0x64, 0x6c, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_place_create_service_proto_rawDescOnce sync.Once
	file_place_create_service_proto_rawDescData = file_place_create_service_proto_rawDesc
)

func file_place_create_service_proto_rawDescGZIP() []byte {
	file_place_create_service_proto_rawDescOnce.Do(func() {
		file_place_create_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_create_service_proto_rawDescData)
	})
	return file_place_create_service_proto_rawDescData
}

var file_place_create_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_place_create_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_place_create_service_proto_goTypes = []interface{}{
	(PlaceCreateServiceEventType)(0),     // 0: place.service.create.PlaceCreateServiceEventType
	(*CreatePlaceListRequest)(nil),       // 1: place.service.create.CreatePlaceListRequest
	(*CreatePlaceListResponse)(nil),      // 2: place.service.create.CreatePlaceListResponse
	(*CreatePlaceListRequest_Place)(nil), // 3: place.service.create.CreatePlaceListRequest.Place
	(*place.Place)(nil),                  // 4: place.Place
}
var file_place_create_service_proto_depIdxs = []int32{
	3, // 0: place.service.create.CreatePlaceListRequest.places:type_name -> place.service.create.CreatePlaceListRequest.Place
	4, // 1: place.service.create.CreatePlaceListResponse.results:type_name -> place.Place
	1, // 2: place.service.create.PlaceCreateService.CreatePlaceList:input_type -> place.service.create.CreatePlaceListRequest
	2, // 3: place.service.create.PlaceCreateService.CreatePlaceList:output_type -> place.service.create.CreatePlaceListResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_place_create_service_proto_init() }
func file_place_create_service_proto_init() {
	if File_place_create_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_create_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_create_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_create_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListRequest_Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_create_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_place_create_service_proto_goTypes,
		DependencyIndexes: file_place_create_service_proto_depIdxs,
		EnumInfos:         file_place_create_service_proto_enumTypes,
		MessageInfos:      file_place_create_service_proto_msgTypes,
	}.Build()
	File_place_create_service_proto = out.File
	file_place_create_service_proto_rawDesc = nil
	file_place_create_service_proto_goTypes = nil
	file_place_create_service_proto_depIdxs = nil
}
