// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: place.service.proto

package place

import (
	common "github.com/knighthell/knighthell-boilerplate-idl-proto/common"
	place "github.com/knighthell/knighthell-boilerplate-idl-proto/place"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceServiceRequestEventType int32

const (
	PlaceServiceRequestEventType_CREATE_PLACE PlaceServiceRequestEventType = 0
	PlaceServiceRequestEventType_READ_PLACE   PlaceServiceRequestEventType = 1
	PlaceServiceRequestEventType_UPDATE_PLACE PlaceServiceRequestEventType = 2
	PlaceServiceRequestEventType_DELETE_PLACE PlaceServiceRequestEventType = 3
)

// Enum value maps for PlaceServiceRequestEventType.
var (
	PlaceServiceRequestEventType_name = map[int32]string{
		0: "CREATE_PLACE",
		1: "READ_PLACE",
		2: "UPDATE_PLACE",
		3: "DELETE_PLACE",
	}
	PlaceServiceRequestEventType_value = map[string]int32{
		"CREATE_PLACE": 0,
		"READ_PLACE":   1,
		"UPDATE_PLACE": 2,
		"DELETE_PLACE": 3,
	}
)

func (x PlaceServiceRequestEventType) Enum() *PlaceServiceRequestEventType {
	p := new(PlaceServiceRequestEventType)
	*p = x
	return p
}

func (x PlaceServiceRequestEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaceServiceRequestEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_place_service_proto_enumTypes[0].Descriptor()
}

func (PlaceServiceRequestEventType) Type() protoreflect.EnumType {
	return &file_place_service_proto_enumTypes[0]
}

func (x PlaceServiceRequestEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaceServiceRequestEventType.Descriptor instead.
func (PlaceServiceRequestEventType) EnumDescriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{0}
}

type PlaceServiceResponseEventType int32

const (
	PlaceServiceResponseEventType_PLACE_CREATED PlaceServiceResponseEventType = 0
	PlaceServiceResponseEventType_PLACE_READ    PlaceServiceResponseEventType = 1
	PlaceServiceResponseEventType_PLACE_UPDATED PlaceServiceResponseEventType = 2
	PlaceServiceResponseEventType_PLACE_DELETED PlaceServiceResponseEventType = 3
)

// Enum value maps for PlaceServiceResponseEventType.
var (
	PlaceServiceResponseEventType_name = map[int32]string{
		0: "PLACE_CREATED",
		1: "PLACE_READ",
		2: "PLACE_UPDATED",
		3: "PLACE_DELETED",
	}
	PlaceServiceResponseEventType_value = map[string]int32{
		"PLACE_CREATED": 0,
		"PLACE_READ":    1,
		"PLACE_UPDATED": 2,
		"PLACE_DELETED": 3,
	}
)

func (x PlaceServiceResponseEventType) Enum() *PlaceServiceResponseEventType {
	p := new(PlaceServiceResponseEventType)
	*p = x
	return p
}

func (x PlaceServiceResponseEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaceServiceResponseEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_place_service_proto_enumTypes[1].Descriptor()
}

func (PlaceServiceResponseEventType) Type() protoreflect.EnumType {
	return &file_place_service_proto_enumTypes[1]
}

func (x PlaceServiceResponseEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaceServiceResponseEventType.Descriptor instead.
func (PlaceServiceResponseEventType) EnumDescriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{1}
}

type CreatePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*CreatePlaceListRequest_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *CreatePlaceListRequest) Reset() {
	*x = CreatePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListRequest) ProtoMessage() {}

func (x *CreatePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePlaceListRequest) GetPlaces() []*CreatePlaceListRequest_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type CreatePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*place.Place `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CreatePlaceListResponse) Reset() {
	*x = CreatePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListResponse) ProtoMessage() {}

func (x *CreatePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlaceListResponse) GetResults() []*place.Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadPlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places                []*ReadPlaceListRequest_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	Keywords              *string                       `protobuf:"bytes,2,opt,name=keywords,proto3,oneof" json:"keywords,omitempty"` // 검색 InputText에 넣은 그대로의 값
	CreatedAtPeriod       *common.Period                `protobuf:"bytes,3,opt,name=createdAtPeriod,proto3,oneof" json:"createdAtPeriod,omitempty"`
	UpdatedAtPeriod       *common.Period                `protobuf:"bytes,4,opt,name=updatedAtPeriod,proto3,oneof" json:"updatedAtPeriod,omitempty"`
	DeletedAtPeriod       *common.Period                `protobuf:"bytes,5,opt,name=deletedAtPeriod,proto3,oneof" json:"deletedAtPeriod,omitempty"`
	IsIncludeDeletedPlace *bool                         `protobuf:"varint,6,opt,name=isIncludeDeletedPlace,proto3,oneof" json:"isIncludeDeletedPlace,omitempty"`
	BoundSquare           *BoundSquare                  `protobuf:"bytes,7,opt,name=boundSquare,proto3,oneof" json:"boundSquare,omitempty"`
	BoundCircle           *BoundCircle                  `protobuf:"bytes,8,opt,name=boundCircle,proto3,oneof" json:"boundCircle,omitempty"`
}

func (x *ReadPlaceListRequest) Reset() {
	*x = ReadPlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceListRequest) ProtoMessage() {}

func (x *ReadPlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceListRequest.ProtoReflect.Descriptor instead.
func (*ReadPlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadPlaceListRequest) GetPlaces() []*ReadPlaceListRequest_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *ReadPlaceListRequest) GetKeywords() string {
	if x != nil && x.Keywords != nil {
		return *x.Keywords
	}
	return ""
}

func (x *ReadPlaceListRequest) GetCreatedAtPeriod() *common.Period {
	if x != nil {
		return x.CreatedAtPeriod
	}
	return nil
}

func (x *ReadPlaceListRequest) GetUpdatedAtPeriod() *common.Period {
	if x != nil {
		return x.UpdatedAtPeriod
	}
	return nil
}

func (x *ReadPlaceListRequest) GetDeletedAtPeriod() *common.Period {
	if x != nil {
		return x.DeletedAtPeriod
	}
	return nil
}

func (x *ReadPlaceListRequest) GetIsIncludeDeletedPlace() bool {
	if x != nil && x.IsIncludeDeletedPlace != nil {
		return *x.IsIncludeDeletedPlace
	}
	return false
}

func (x *ReadPlaceListRequest) GetBoundSquare() *BoundSquare {
	if x != nil {
		return x.BoundSquare
	}
	return nil
}

func (x *ReadPlaceListRequest) GetBoundCircle() *BoundCircle {
	if x != nil {
		return x.BoundCircle
	}
	return nil
}

type ReadPlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseInfo *common.ResponseInfo `protobuf:"bytes,1,opt,name=responseInfo,proto3" json:"responseInfo,omitempty"`
	Places       []*place.Place       `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *ReadPlaceListResponse) Reset() {
	*x = ReadPlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceListResponse) ProtoMessage() {}

func (x *ReadPlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceListResponse.ProtoReflect.Descriptor instead.
func (*ReadPlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadPlaceListResponse) GetResponseInfo() *common.ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *ReadPlaceListResponse) GetPlaces() []*place.Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type UpdatePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*UpdatePlaceListRequest_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *UpdatePlaceListRequest) Reset() {
	*x = UpdatePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceListRequest) ProtoMessage() {}

func (x *UpdatePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceListRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePlaceListRequest) GetPlaces() []*UpdatePlaceListRequest_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type UpdatePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*place.Place `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *UpdatePlaceListResponse) Reset() {
	*x = UpdatePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceListResponse) ProtoMessage() {}

func (x *UpdatePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceListResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePlaceListResponse) GetResults() []*place.Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeletePlaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*DeletePlaceListRequest_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *DeletePlaceListRequest) Reset() {
	*x = DeletePlaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceListRequest) ProtoMessage() {}

func (x *DeletePlaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceListRequest.ProtoReflect.Descriptor instead.
func (*DeletePlaceListRequest) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePlaceListRequest) GetPlaces() []*DeletePlaceListRequest_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type DeletePlaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*place.Place `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *DeletePlaceListResponse) Reset() {
	*x = DeletePlaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceListResponse) ProtoMessage() {}

func (x *DeletePlaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceListResponse.ProtoReflect.Descriptor instead.
func (*DeletePlaceListResponse) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePlaceListResponse) GetResults() []*place.Place {
	if x != nil {
		return x.Results
	}
	return nil
}

type BoundSquare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopRight   *place.Wgs84Coordinates `protobuf:"bytes,1,opt,name=topRight,proto3" json:"topRight,omitempty"`
	BottomLeft *place.Wgs84Coordinates `protobuf:"bytes,2,opt,name=bottomLeft,proto3" json:"bottomLeft,omitempty"`
}

func (x *BoundSquare) Reset() {
	*x = BoundSquare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundSquare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundSquare) ProtoMessage() {}

func (x *BoundSquare) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundSquare.ProtoReflect.Descriptor instead.
func (*BoundSquare) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{8}
}

func (x *BoundSquare) GetTopRight() *place.Wgs84Coordinates {
	if x != nil {
		return x.TopRight
	}
	return nil
}

func (x *BoundSquare) GetBottomLeft() *place.Wgs84Coordinates {
	if x != nil {
		return x.BottomLeft
	}
	return nil
}

type BoundCircle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Center      *place.Wgs84Coordinates `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusMeter int32                   `protobuf:"varint,2,opt,name=radiusMeter,proto3" json:"radiusMeter,omitempty"`
}

func (x *BoundCircle) Reset() {
	*x = BoundCircle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundCircle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundCircle) ProtoMessage() {}

func (x *BoundCircle) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundCircle.ProtoReflect.Descriptor instead.
func (*BoundCircle) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{9}
}

func (x *BoundCircle) GetCenter() *place.Wgs84Coordinates {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *BoundCircle) GetRadiusMeter() int32 {
	if x != nil {
		return x.RadiusMeter
	}
	return 0
}

type CreatePlaceListRequest_Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // 장소(Place)의 원래 이름
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`   // 장소(Place)의 위도
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"` // 장소(Place)의 경도
}

func (x *CreatePlaceListRequest_Place) Reset() {
	*x = CreatePlaceListRequest_Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaceListRequest_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaceListRequest_Place) ProtoMessage() {}

func (x *CreatePlaceListRequest_Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaceListRequest_Place.ProtoReflect.Descriptor instead.
func (*CreatePlaceListRequest_Place) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreatePlaceListRequest_Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlaceListRequest_Place) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePlaceListRequest_Place) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ReadPlaceListRequest_Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId string `protobuf:"bytes,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
}

func (x *ReadPlaceListRequest_Place) Reset() {
	*x = ReadPlaceListRequest_Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPlaceListRequest_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlaceListRequest_Place) ProtoMessage() {}

func (x *ReadPlaceListRequest_Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlaceListRequest_Place.ProtoReflect.Descriptor instead.
func (*ReadPlaceListRequest_Place) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReadPlaceListRequest_Place) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type UpdatePlaceListRequest_Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId   string   `protobuf:"bytes,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	Name      *string  `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`             // 장소(Place)의 원래 이름(No Localization Name)
	Latitude  *float64 `protobuf:"fixed64,3,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`   // 장소(Place)의 위도
	Longitude *float64 `protobuf:"fixed64,4,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"` // 장소(Place)의 경도
}

func (x *UpdatePlaceListRequest_Place) Reset() {
	*x = UpdatePlaceListRequest_Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaceListRequest_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaceListRequest_Place) ProtoMessage() {}

func (x *UpdatePlaceListRequest_Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaceListRequest_Place.ProtoReflect.Descriptor instead.
func (*UpdatePlaceListRequest_Place) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdatePlaceListRequest_Place) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *UpdatePlaceListRequest_Place) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePlaceListRequest_Place) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdatePlaceListRequest_Place) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type DeletePlaceListRequest_Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId string `protobuf:"bytes,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
}

func (x *DeletePlaceListRequest_Place) Reset() {
	*x = DeletePlaceListRequest_Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlaceListRequest_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaceListRequest_Place) ProtoMessage() {}

func (x *DeletePlaceListRequest_Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaceListRequest_Place.ProtoReflect.Descriptor instead.
func (*DeletePlaceListRequest_Place) Descriptor() ([]byte, []int) {
	return file_place_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DeletePlaceListRequest_Place) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

var File_place_service_proto protoreflect.FileDescriptor

var file_place_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x1a, 0x13, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2d, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0c, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x1a, 0x55, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x86,
	0x05, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x1f, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x48, 0x01, 0x52, 0x0f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x3d, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x48, 0x02, 0x52, 0x0f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x3d, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x48, 0x03, 0x52, 0x0f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x39, 0x0a, 0x15, 0x69, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x04, 0x52, 0x15, 0x69, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x0b, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x48, 0x05, 0x52, 0x0b, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x0b, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43,
	0x69, 0x72, 0x63, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x48,
	0x06, 0x52, 0x0b, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x88, 0x01,
	0x01, 0x1a, 0x21, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x18, 0x0a,
	0x16, 0x5f, 0x69, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x22, 0x77, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x22, 0xfa, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x1a, 0xa2, 0x01, 0x0a, 0x05, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x41, 0x0a,
	0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x22, 0x78, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52,
	0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x21, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x17, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x7b, 0x0a,
	0x0b, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12, 0x33, 0x0a, 0x08,
	0x74, 0x6f, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x57, 0x67, 0x73, 0x38, 0x34, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x37, 0x0a, 0x0a, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x57, 0x67,
	0x73, 0x38, 0x34, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0a,
	0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x22, 0x60, 0x0a, 0x0b, 0x42, 0x6f,
	0x75, 0x6e, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x57, 0x67, 0x73, 0x38, 0x34, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2a, 0x64, 0x0a, 0x1c,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45,
	0x10, 0x03, 0x2a, 0x68, 0x0a, 0x1d, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x5f, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x5f,
	0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x5f,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4c, 0x41,
	0x43, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x32, 0xd0, 0x02, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x68, 0x65, 0x6c, 0x6c, 0x2f, 0x6b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68,
	0x65, 0x6c, 0x6c, 0x2d, 0x62, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2d,
	0x69, 0x64, 0x6c, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_place_service_proto_rawDescOnce sync.Once
	file_place_service_proto_rawDescData = file_place_service_proto_rawDesc
)

func file_place_service_proto_rawDescGZIP() []byte {
	file_place_service_proto_rawDescOnce.Do(func() {
		file_place_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_service_proto_rawDescData)
	})
	return file_place_service_proto_rawDescData
}

var file_place_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_place_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_place_service_proto_goTypes = []interface{}{
	(PlaceServiceRequestEventType)(0),    // 0: place.PlaceServiceRequestEventType
	(PlaceServiceResponseEventType)(0),   // 1: place.PlaceServiceResponseEventType
	(*CreatePlaceListRequest)(nil),       // 2: place.CreatePlaceListRequest
	(*CreatePlaceListResponse)(nil),      // 3: place.CreatePlaceListResponse
	(*ReadPlaceListRequest)(nil),         // 4: place.ReadPlaceListRequest
	(*ReadPlaceListResponse)(nil),        // 5: place.ReadPlaceListResponse
	(*UpdatePlaceListRequest)(nil),       // 6: place.UpdatePlaceListRequest
	(*UpdatePlaceListResponse)(nil),      // 7: place.UpdatePlaceListResponse
	(*DeletePlaceListRequest)(nil),       // 8: place.DeletePlaceListRequest
	(*DeletePlaceListResponse)(nil),      // 9: place.DeletePlaceListResponse
	(*BoundSquare)(nil),                  // 10: place.BoundSquare
	(*BoundCircle)(nil),                  // 11: place.BoundCircle
	(*CreatePlaceListRequest_Place)(nil), // 12: place.CreatePlaceListRequest.Place
	(*ReadPlaceListRequest_Place)(nil),   // 13: place.ReadPlaceListRequest.Place
	(*UpdatePlaceListRequest_Place)(nil), // 14: place.UpdatePlaceListRequest.Place
	(*DeletePlaceListRequest_Place)(nil), // 15: place.DeletePlaceListRequest.Place
	(*place.Place)(nil),                  // 16: place.Place
	(*common.Period)(nil),                // 17: common.Period
	(*common.ResponseInfo)(nil),          // 18: common.ResponseInfo
	(*place.Wgs84Coordinates)(nil),       // 19: place.Wgs84Coordinates
}
var file_place_service_proto_depIdxs = []int32{
	12, // 0: place.CreatePlaceListRequest.places:type_name -> place.CreatePlaceListRequest.Place
	16, // 1: place.CreatePlaceListResponse.results:type_name -> place.Place
	13, // 2: place.ReadPlaceListRequest.places:type_name -> place.ReadPlaceListRequest.Place
	17, // 3: place.ReadPlaceListRequest.createdAtPeriod:type_name -> common.Period
	17, // 4: place.ReadPlaceListRequest.updatedAtPeriod:type_name -> common.Period
	17, // 5: place.ReadPlaceListRequest.deletedAtPeriod:type_name -> common.Period
	10, // 6: place.ReadPlaceListRequest.boundSquare:type_name -> place.BoundSquare
	11, // 7: place.ReadPlaceListRequest.boundCircle:type_name -> place.BoundCircle
	18, // 8: place.ReadPlaceListResponse.responseInfo:type_name -> common.ResponseInfo
	16, // 9: place.ReadPlaceListResponse.places:type_name -> place.Place
	14, // 10: place.UpdatePlaceListRequest.places:type_name -> place.UpdatePlaceListRequest.Place
	16, // 11: place.UpdatePlaceListResponse.results:type_name -> place.Place
	15, // 12: place.DeletePlaceListRequest.places:type_name -> place.DeletePlaceListRequest.Place
	16, // 13: place.DeletePlaceListResponse.results:type_name -> place.Place
	19, // 14: place.BoundSquare.topRight:type_name -> place.Wgs84Coordinates
	19, // 15: place.BoundSquare.bottomLeft:type_name -> place.Wgs84Coordinates
	19, // 16: place.BoundCircle.center:type_name -> place.Wgs84Coordinates
	2,  // 17: place.PlaceService.CreatePlaceList:input_type -> place.CreatePlaceListRequest
	4,  // 18: place.PlaceService.ReadPlaceList:input_type -> place.ReadPlaceListRequest
	6,  // 19: place.PlaceService.UpdatePlaceList:input_type -> place.UpdatePlaceListRequest
	8,  // 20: place.PlaceService.DeletePlaceList:input_type -> place.DeletePlaceListRequest
	3,  // 21: place.PlaceService.CreatePlaceList:output_type -> place.CreatePlaceListResponse
	5,  // 22: place.PlaceService.ReadPlaceList:output_type -> place.ReadPlaceListResponse
	7,  // 23: place.PlaceService.UpdatePlaceList:output_type -> place.UpdatePlaceListResponse
	9,  // 24: place.PlaceService.DeletePlaceList:output_type -> place.DeletePlaceListResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_place_service_proto_init() }
func file_place_service_proto_init() {
	if File_place_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundSquare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundCircle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaceListRequest_Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPlaceListRequest_Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaceListRequest_Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlaceListRequest_Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_place_service_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_place_service_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_place_service_proto_goTypes,
		DependencyIndexes: file_place_service_proto_depIdxs,
		EnumInfos:         file_place_service_proto_enumTypes,
		MessageInfos:      file_place_service_proto_msgTypes,
	}.Build()
	File_place_service_proto = out.File
	file_place_service_proto_rawDesc = nil
	file_place_service_proto_goTypes = nil
	file_place_service_proto_depIdxs = nil
}
